### ISSUE TITLE
flux support

### ISSUE THREAD

**Issue by stasiek** [Transatel/cleanflux#6]
Any plans for flux Query Language support?

**Comment by p3r7** [comment]
nope.

i don't work anymore for the company in which i built this tool and flux support would be an hell on an undertaking.

the hard hard part would be making a flux query parser in python to manipulate it as an AST.

an alt route would be redoing cleanflux in golang to rely on the same flux [parser](https://github.com/influxdata/flux/tree/master/libflux/flux-core/src/parser) & [AST](https://github.com/influxdata/flux/tree/master/ast) libs as InfluxDB itself does.

my limited xp w/ tree traversal in go is that it's super verbose and often nightmarish (when it depends on dynamic typing through `interface{}`).

**Comment by stasiek** [comment]
ACK!

Thanks for replying!
